In [9]:
#To creating an ndarray
import numpy as np
arr=np.array([10,20,30,40])
print(arr)
print(type(arr))
print(np.__version__)

[10 20 30 40]
<class 'numpy.ndarray'>
1.23.5


In [ ]:
#Dimensions in Array

In [9]:
arr=np.array(10)
print(arr)
print(arr.ndim)
arr1=np.array([10,20,30,40])
print(arr1)
print(arr1.ndim)
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.ndim)
arr3=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)
print(arr3.ndim)

10
0
[10 20 30 40]
1
[[1 2 3]
 [4 5 6]]
2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [12]:
arr4=np.array([1,2,3,4],ndmin=10)
print(arr4)
print("Number of dimensions::",arr4.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
Number of dimensions:: 10


In [20]:
#Access the array elements
print(arr1)
print(arr1[0])
print(arr1[0:3])
print(arr1[-3:-1])
print(arr1[::2])
print(arr1[0]+arr1[1])

[10 20 30 40]
10
[10 20 30]
[20 30]
[10 30]
30


In [31]:
#Access the elements on the first row and second column
arr5=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print('2nd element on 1st row:',arr5[2,0])

2nd element on 1st row: 11


In [5]:
#Copy
arr=np.array([10,20,30,40])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42 20 30 40]
[10 20 30 40]


In [8]:
arr=np.array([10,20,30,40])
x=arr.view()
arr[0]=42
print(arr)
print(x)
print(x.base)
#print(arr.base)

[42 20 30 40]
[42 20 30 40]
[42 20 30 40]
None


In [14]:
print(arr.shape)

(4,)


In [18]:
#Reshaping from 1d and 2d
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [21]:
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [22]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [25]:
#Join two 2-D arrays along rows(axis=1)
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#Stack Function

In [ ]:
# Stacking is same as concatenation the only different is that stacking is done along a new axis

In [1]:
import numpy as np

In [4]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [5]:
#Stack along with rows
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [6]:
#Stack along with columns
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
#Stacking along height(Depth)
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [15]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,2)
#newarr1=np.hsplit(arr,3)
#newarr1=np.vsplit(arr,2)
print(newarr)
#print(newarr1)

[array([1, 2, 3]), array([4, 5, 6])]


In [19]:
#Searching Arrays
arr=np.array([1,4,2,4,5,4,4])
#x=np.where(arr==4)
x=np.where(arr%2==1)
print(x)

(array([0, 4], dtype=int64),)


In [23]:
arr=np.array([6,7,8,9])
#x=np.searchsorted(arr,7,side='right')
x=np.searchsorted(arr,[6,7,8])
print(x)

[0 1 2]


In [ ]:
#Task
#Sort

In [25]:
#Filtering Arrays
arr=np.array([41,42,43,44])
x=[True,False,True,True]
newarr=arr[x]
print(newarr)

[41 43 44]


In [59]:
#Generate Random Number
from numpy import random
x=random.randint(10,size=(2,10))
x

array([[5, 4, 1, 2, 0, 5, 4, 5, 1, 8],
       [0, 9, 4, 2, 8, 1, 0, 7, 6, 8]])